name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_speed_dial: ^7.0.0
  go_router: ^9.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
    - family: BarbieFont
      fonts:
        - asset: assets/fonts/BarbieFont.ttf

  assets:
    - assets/images/
